Frontend added
NER-w/NeRw pull request #4
Opened 2023-06-01 11:33 UTC by EGheska

React application was created.
Node modules doesn't included
src contains components and .js files contains pages
index.html is filled

2023-06-01 11:38 UTC, jurijjzz approved these changes

2023-06-01 11:45 UTC, 06Pac requested changes

2023-06-01 11:45 UTC, 06Pac commented on frontend/src/App.js
> +export default App;
Wrap app into observer

2023-06-01 11:45 UTC, 06Pac commented on frontend/src/components/header/navbar.js
> +
Add second option, when user is not logged in

2023-06-01 12:15 UTC, NeuroCorgi requested changes

2023-06-01 12:15 UTC, NeuroCorgi commented on frontend/package-lock.json
Remove this file, it is not needed

2023-06-01 12:15 UTC, NeuroCorgi commented on frontend/public/favicon.ico
Is it really needed?

2023-06-01 12:15 UTC, NeuroCorgi commented on frontend/src/components/body/body.jsx
Maybe add more semantic tags?

2023-06-01 12:15 UTC, NeuroCorgi commented on frontend/src/components/body/body_style.css
Think about switching to tailwind or (forgive me) ~~bootstrap~~

2023-06-01 12:15 UTC, NeuroCorgi commented on frontend/src/components/header/header.js
Eliminate dead code

2023-06-01 12:15 UTC, NeuroCorgi commented on frontend/src/components/header/style.css
Same as main css. Think about tailwind(~~bootstrap~~)

2023-06-01 12:20 UTC, jurijjzz approved these changes
fix it please

2023-06-01 12:20 UTC, jurijjzz requested changes
fix it please

2023-06-01 12:21 UTC, 06Pac reviewed
Make logic names for component folders like section, bars, menu ......

2023-06-01 12:26 UTC, 06Pac reviewed
Make logic names for component folders like section, bars, menu ......

2023-06-01 12:26 UTC, 06Pac commented on frontend/src/pages/user.js
> +
Change type to jsx

2023-06-06 21:14 UTC, NeuroCorgi requested changes
New files in 'forms' directory are empty

2023-06-06 21:14 UTC, NeuroCorgi commented on frontend/package-lock.json
Remove this file

2023-06-08 15:51 UTC, jurijjzz approved these changes

2023-06-08 15:52 UTC, NeuroCorgi approved these changes

2023-06-08 15:52 UTC, 06Pac approved these changes

2023-06-08 15:53 UTC, merged